### ISSUE TITLE
CircleCI Issues apparently capped at 30

### ISSUE THREAD

**Issue by matthew-piziak** [vermiculus/ghub-plus#10]
I'm not sure if this is a MagitHub issue or a ghubp issue.

My `Status` header reports `Failure (30/30)`. I have more than thirty tests, but only only thirty of them show up in the status section, all of which are passing. One of the hidden ones is failing, which results in the confusing status. On github.com, the CircleCI widget shows all of my tests. Is there some pagination here that is not being properly handled?

This form...
```emacs-lisp
(length 
  (assoc 'statuses 
    (ghubp-get-repos-owner-repo-commits-ref-status 
      (magithub-repo) 
      (magithub-ci-status--get-default-ref))))
```
...evaluates to 31.

**Comment by matthew-piziak** [comment]
I wonder if it has anything to do with the fact that CircleCI is currently "Experiencing Issues with GitHub".

**Comment by vermiculus** [comment]
No, that's probably not it (the CircleCI experiencing issues with GitHub). I don't think I ever considered there could be more than one page of statuses (wow!). It just needs to be unpaginated. Thanks for the report.

**Comment by vermiculus** [comment]
Do you have a repo+hash I can use for testing?

**Comment by vermiculus** [comment]
Duplicate vermiculus/magithub#370, but I'll keep the conversation here.

**Comment by matthew-piziak** [comment]
Thanks for the fast response!

Unfortunately the tested repo is private and I am not at liberty to grant you access. It is indeed quite thoroughly tested, hehe. As for `ghub-plus` itself, I am using the latest version of `magithub` on GitHub (https://github.com/vermiculus/magithub/commit/9be91acd1ecc06cfcfab7912821a08cbf1b1fff2), installed with `(use-package magithub :straight t)`.

Any way I can help you with this?

**Comment by vermiculus** [comment]
I can try manually posting a bunch of statuses to vermiculus/my-new-repository@deadbeef for testing.

**Comment by matthew-piziak** [comment]
Good idea. In the meantime I'll try to hack in a `?per_page=100` parameter somewhere, see if that fixes my repo. I'll let you know how that goes.

**Comment by matthew-piziak** [comment]
I'm having trouble finding a good place to hack it in though...got any candidates? I see it might also be a case of passing `unpaginate t` somewhere.

**Comment by matthew-piziak** [comment]
Or `ghubp-unpaginate`. My Emacs Lisp is pretty weak unfortunately.

**Comment by matthew-piziak** [comment]
I tried this:
```
(defmacro magithub-request (&rest body)
  "Execute BODY authenticating as Magithub."
  (declare (debug t))
  `(ghubp-override-context unpaginate t
     (ghubp-override-context auth 'magithub
       ,@body)))
```
Where I added the `unpaginate t` override. But no dice.

**Comment by vermiculus** [comment]
After defining that macro you would have to recompile magithub. You should rather try advising the status-retrieval stuff.

**Comment by matthew-piziak** [comment]
Ah. Mind pointing me to the right function?

**Comment by matthew-piziak** [comment]
I tried redefining `magithub-request` and then recompiling `magithub` with `(usepackage magithub :straight t)`, but that didn't do it.

**Comment by matthew-piziak** [comment]
I tried redefining `magithub-request` and then recompiling `magithub` with `(usepackage magithub :straight t)`, but that didn't do it.

**Comment by vermiculus** [comment]
Sorry, I've been out and about most of the day. The function you want to advise is `magithub-ci-status`.

**Comment by matthew-piziak** [comment]
No need to apologize! I appreciate the help. 

This doesn't seem to work:
```emacs-lisp
(defun magithub-ci-status (ref)
  (when (stringp ref)
    (if (magit-rebase-in-progress-p)
        ;; avoid rate-limiting ourselves
        (magithub-debug-message "skipping CI status checks while in rebase")
      (or (magithub-cache :ci-status
            `(ghubp-override-context unpaginate t (magithub-request
						   (ghubp-get-repos-owner-repo-commits-ref-status
						       ',(magithub-repo) ,ref)))
            :message
            (format "Getting CI status for %s..."
                    (if (magit-branch-p ref) (format "branch `%s'" ref)
		      (substring ref 0 6)))
            :after-update
            (lambda (status &rest _)
	      (setf (magithub-ci--status-last-refreshed-time (magithub-repo) ref)
                    (current-time))
	      (message "(magithub): new statuses retrieved -- overall: %s"
		       (alist-get 'state status))))
          '((state . "error")
            (total_count . 0)
            (magithub-message . "ref not found on remote"))))))
```

I've added `(ghubp-override-context unpaginate t ...` to the `magithub-request` call.

**Comment by matthew-piziak** [comment]
Another issue that that I'm not always seeing the CI reports agree with upstream. Possibly some kind of caching issue. Is deleting `~/.emacs.d/magithub/cache` sufficient to invalidate the cache?

**Comment by vermiculus** [comment]
Or just g on the section

**Comment by matthew-piziak** [comment]
I'm definitely seeing some odd behavior...some more info here: https://github.com/vermiculus/magithub/issues/308#issuecomment-421139500

Do you see anything wrong with how I enabled unpagination?

**Comment by matthew-piziak** [comment]
I'd like to help fix this but I don't know the architecture well enough. Is there something wrong with adding `hgubp-override-context unpaginate t` to the `magithub-request` call for CI statuses? If we can't unpaginate in general, I think the logic for the overall status needs to be updated.

**Comment by vermiculus** [comment]
There's nothing wrong with that approach if that fixes the problem

**Comment by matthew-piziak** [comment]
Hmm. It _doesn't_ unfortunately. I assumed I was making a dumb language error or something.

**Comment by matthew-piziak** [comment]
I'm definitely binding it correctly. I added a print statement to make sure. ...the most powerful debugging tool.

**Comment by vermiculus** [comment]
Try using :unpaginate instead of unpaginate

**Comment by vermiculus** [comment]
Oh if you've verified that the state is getting passed down correctly then yeah I dunno

**Comment by matthew-piziak** [comment]
Oh that's different.
```
‘ghubp-override-context’ should only override one of the symbols from ‘ghubp-contextualize-function’.
```

**Comment by matthew-piziak** [comment]
The other override is presumably `auth 'magithub`.

**Comment by matthew-piziak** [comment]
But I can't do two overrides? That seems wrong, no?

**Comment by vermiculus** [comment]
You definitely can; there are other calls to ghubp-unpaginate in the codebase that surround magithub-request

**Comment by matthew-piziak** [comment]
Oh okay! I did `ghubp-unpaginate` instead and that doesn't error out. The status bar is still wrong, though.

**Comment by matthew-piziak** [comment]
When I run `(length (alist-get 'statuses (magithub-ci-status (magithub-ci-status--get-default-ref))))` I still get 30. Hmm.

**Comment by matthew-piziak** [comment]
Here's the request in `*Messages*`:
```
magithub: (36:55.251) ghub-request("GET" "/repos/redacted" nil :query nil :payload nil :unpaginate t :headers nil :username nil :auth magithub :host nil)
```

**Comment by vermiculus** [comment]
from that debug statement, we do indeed unpaginate the request. I'm wondering if it's possible the API simply isn't equipped for this case. If you use any other github clients that display status, I assume those work?

**Comment by matthew-piziak** [comment]
I'm not sure. I'll try with RESTclient.

**Comment by matthew-piziak** [comment]
Hmm. I'm getting tripped up with the auth. I can't get a restclient request working to test.

**Comment by vermiculus** [comment]
Do you need auth for getting statuses? Or is it a private repo on github.com?

**Comment by matthew-piziak** [comment]
It's a private repo. However, I'm tempted to go look for a public repo with a lot of tests so that there's something we can share.

**Comment by matthew-piziak** [comment]
Here's one: https://github.com/electron

They have just over one page of tests.

**Comment by matthew-piziak** [comment]
Hmm. Looks like 35 in PRs but I see 25/25 in Magit. I'll look for a bigger repo.

**Comment by matthew-piziak** [comment]
Hmm. Looks like 35 in PRs but I see 25/25 in Magit. I'll look for a bigger repo.

**Comment by matthew-piziak** [comment]
Hmm, I can't find one! I wonder if it replicates for other CI providers.

**Comment by vermiculus** [comment]
I think it may be in fact a bug in GitHub's API. Details incoming.

**Comment by vermiculus** [comment]
Yeah, we get `30` for `total_count`, so presumably the API only knows about 30 statuses (i.e., one page).

```sh
$ curl -s https://api.github.com/repos/electron/electron/commits/dee311548373e78d8625c6b35d31c2dc658b8110/status \
 | jq .total_count
30
```

<img width="585" alt="image" src="https://user-images.githubusercontent.com/2082195/46175859-06729400-c273-11e8-9809-256f9f36d229.png">

I'm going to follow up with GitHub.

**Comment by vermiculus** [comment]
They replied this morning:

![image](https://user-images.githubusercontent.com/2082195/46370631-afdad080-c64b-11e8-9729-6620c263ccd5.png)

I've asked them to let me know if this ever changes. I'm going to close this issue for now.

**Comment by matthew-piziak** [comment]
Oof, that's a disheartening reply from upstream. "Our API is definitely broken but I can't promise we'll ever fix it."

Thanks very much for looking into this. Hopefully they'll make it better one day.

**Comment by vermiculus** [comment]
I understand their POV. They need to evaluate whether any applications may be depending on the bug *and* the effort required to fix that bug considering they want to be pushing v4 of their API. I hope they do fix it, but their situation is understandable :)

**Comment by matthew-piziak** [comment]
Such is the life of enterprise software. Definitely relatable.
