### ISSUE TITLE
Error on latest code

### ISSUE THREAD

**Issue by qhuyduong** [vermiculus/ghub-plus#13]
After fetching latest code it got this error everytime 
```elisp
(error ":condition-case must be a list of error handlers; see the documentation: ((ghub-422 (signal 'ghubp-error-review-is-active nil)) (ghub-http-error (let* ((val (car (cdr it)))) (if (eq val 422) (progn (signal 'ghubp-error-review-is-active nil)) (signal (car it) (cdr it))))))")
```

**Comment by cdlm** [comment]
Travis failed because of it, and since a similar oversight happened somewhen in march, I wonder if a unit test or some flycheck rule would help…

**Comment by seagle0128** [comment]
Same issue here. `magithub` doesn't work anymore.

**Comment by vermiculus** [comment]
I don't use flycheck, but this should have be caught by the compile-on-save functionality I have set up. I should've run the tests before pushing, though; this is caught by those.

**Comment by vermiculus** [comment]
Although strangely, this should be working. I'm not sure why/how the `ghub-422` symbol is being constructed. I don't have my development environment with me though, so I won't be able to look at it for about eight hours. If someone wants to take up a fix, I would start by looking at the macro-expansion of `ghubp-catch*`.

**Comment by vermiculus** [comment]
We might need to do away with older Ghub support:

https://github.com/vermiculus/ghub-plus/blob/b3a90d107bc502259b17ea4f01b0bee148a57428/ghub%2B.el#L138

**Comment by vermiculus** [comment]
Probably will need an edit to `ghubp--catch`.

**Comment by vermiculus** [comment]
Should be fixed now; it will take a few hours to propagate to MELPA.
