### ISSUE TITLE
Please bump 'Package-Version' to reflect release versioning

### ISSUE THREAD

**Issue by mfvescovi** [vermiculus/ghub-plus#5]
In .el file ';; Package-Version: 0.1' is supposed to be 0.1.5 and be updated on new releases.
This could help me to avoid patching the code for every release, as I am doing with [this.](https://anonscm.debian.org/cgit/pkg-emacsen/pkg/ghub-plus-el.git/tree/debian/patches/0001-Fix_package_version.patch?id=192ea480040a335c4d175ff7734b9172a73ee7ac).
Thanks.

**Comment by vermiculus** [comment]
Bumped to 0.2 with all the cool new stuff that's been added. See e04050f81106029c342deb7adbfc67b2a888ec58.

Related to vermiculus/apiwrap.el#7 – I need to figure out a way to avoid doing this again and again.
