### ISSUE TITLE
Line feeds should be placed on separate lines

### ISSUE THREAD

**Issue by tarsius** [vermiculus/ghub-plus#6]
You are using section headings like

```
;;; Utilities
```

That messes with `outline-minor-mode`.  You could probably set `outline-regexp` locally to deal with this, but I would recommened just inserting a newline after the line feed.

**Comment by vermiculus** [comment]
I've been using these with my own little navigation toolset -- essentially just filter the buffer to lines that start with a line feed and complete on the result.  Is `outline` the standard approach to this?  The default keybindings seem...cumbersome.

---

On a side note, do you think Magithub should be smart to replace control characters like `` with their string equivalents (`^L`)?  I'm on the fence.

**Comment by tarsius** [comment]
> The default keybindings seem...cumbersome.

I am working on fixing that :wink: 

> replace control characters like ? with

Github did swallow the character. Point me to a line so I can look at it in Emacs.

Edit: Ah! In text it sends... Well given my confusion just now that might be a good idea :stuck_out_tongue:

**Comment by tarsius** [comment]
`Text contains control characters that won't be displayed correctly on Github.  Replace with text representation? (y or n)`

**Comment by vermiculus** [comment]
Yep, my thought exactly. Just trying to find a test that will catch non-printing characters. So far I've found the face `escape-glyph`; looking to see where that's used in src/.
